# Generated by Django 4.0.7 on 2022-10-02 14:10

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
            ],
        ),
    ]
